server:
  port: 8081 # Порт каталога
  address: 0.0.0.0

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5433/salon_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
      timeout: 2000ms
      connect-timeout: 2000ms

  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "salon::"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB