server:
  port: 8083
  address: 0.0.0.0

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://localhost:5433/salon_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Автоматически создаст таблицы, если их нет в БД
    show-sql: true     # Чтобы в консоли было видно, как летят запросы
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 9a4f94d8170b1343feaa84181286e1112233445566778899aabbccddeeff0011
  expiration: 86400000