server:
  port: 8087
  address: 0.0.0.0

spring:
  application:
    name: api-gateway-service
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:9a4f94d8170b1343feaa84181286e1112233445566778899aabbccddeeff0011}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.service.salon: DEBUG
